# Generated by Django 5.1 on 2024-08-15 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand_logo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='images/')),
                ('gender', models.CharField(max_length=50)),
                ('size', models.IntegerField(max_length=10)),
                ('likes', models.IntegerField(max_length=10)),
                ('brandName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brandname')),
            ],
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
