# Generated by Django 5.1 on 2024-08-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brandname_shoe_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='likes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(),
        ),
    ]
