# Generated by Django 5.1 on 2024-08-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shoe_likes_alter_shoe_price_alter_shoe_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='description',
            field=models.TextField(blank=True, default='no description'),
        ),
    ]
